<a href="https://colab.research.google.com/github/abhikhan2999/Pics_detection_using_Ann/blob/main/DL_by_codebasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt

In [4]:
df= pd.read_csv("/content/sonar_dataset.csv", header=None)

In [5]:
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  
4  0.0107  0.0094   R  

[5 rows x 61 columns]

In [7]:
df.shape

(208, 61)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       208 non-null    float64
 1   1       208 non-null    float64
 2   2       208 non-null    float64
 3   3       208 non-null    float64
 4   4       208 non-null    float64
 5   5       208 non-null    float64
 6   6       208 non-null    float64
 7   7       208 non-null    float64
 8   8       208 non-null    float64
 9   9       208 non-null    float64
 10  10      208 non-null    float64
 11  11      208 non-null    float64
 12  12      208 non-null    float64
 13  13      208 non-null    float64
 14  14      208 non-null    float64
 15  15      208 non-null    float64
 16  16      208 non-null    float64
 17  17      208 non-null    float64
 18  18      208 non-null    float64
 19  19      208 non-null    float64
 20  20      208 non-null    float64
 21  21      208 non-null    float64
 22  22

In [9]:
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [10]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [11]:
df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [16]:
X=df.drop(60, axis=1)
y=df[60]
X.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      50      51      52      53      54      55      56  \
0  0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180   
1  0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140   
2  0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316   
3  0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050   
4  0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072   

       57      58      59  
0  0.0084  0.0090  0.0032  
1  0.0049  0.0052  0.0044  
2  0.0164  0.0095  0.0078  
3  0.0044  0.0040  0.0117  
4  0.0048  0.0107  0.0094  

[5 rows x 60 columns]

In [17]:
#To code the y as replaced by 1 and 0
y = pd.get_dummies(y, drop_first=True)
y.sample(5)

R
165  0
67   1
69   1
92   1
187  0

In [18]:
y.value_counts()

R
0    111
1     97
dtype: int64

In [19]:
X.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      50      51      52      53      54      55      56  \
0  0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180   
1  0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140   
2  0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316   
3  0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050   
4  0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072   

       57      58      59  
0  0.0084  0.0090  0.0032  
1  0.0049  0.0052  0.0044  
2  0.0164  0.0095  0.0078  
3  0.0044  0.0040  0.0117  
4  0.0048  0.0107  0.0094  

[5 rows x 60 columns]

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state=1)

In [22]:
X_train.head()

0       1       2       3       4       5       6       7       8   \
67   0.0368  0.0403  0.0317  0.0293  0.0820  0.1342  0.1161  0.0663  0.0155   
14   0.0124  0.0433  0.0604  0.0449  0.0597  0.0355  0.0531  0.0343  0.1052   
164  0.0163  0.0198  0.0202  0.0386  0.0752  0.1444  0.1487  0.1484  0.2442   
179  0.0394  0.0420  0.0446  0.0551  0.0597  0.1416  0.0956  0.0802  0.1618   
19   0.0126  0.0149  0.0641  0.1732  0.2565  0.2559  0.2947  0.4110  0.4983   

         9   ...      50      51      52      53      54      55      56  \
67   0.0506  ...  0.0058  0.0091  0.0160  0.0160  0.0081  0.0070  0.0135   
14   0.2120  ...  0.0078  0.0083  0.0057  0.0174  0.0188  0.0054  0.0114   
164  0.2822  ...  0.0027  0.0077  0.0026  0.0031  0.0083  0.0020  0.0084   
179  0.2558  ...  0.0118  0.0146  0.0040  0.0114  0.0032  0.0062  0.0101   
19   0.5920  ...  0.0153  0.0092  0.0035  0.0098  0.0121  0.0006  0.0181   

         57      58      59  
67   0.0067  0.0078  0.0068  
14   0.0196  0.0147  0.0062  
164  0.0108  0.0083  0.0033  
179  0.0068  0.0053  0.0087  
19   0.0094  0.0116  0.0063  

[5 rows x 60 columns]

In [23]:
y_train.head()

R
67   1
14   1
164  0
179  0
19   1

In [26]:
#Appllyingt the deep learning Model Now with sequenotal Keras
import tensorflow as tf
from tensorflow import keras

In [29]:
# model = keras.Sequential([
#     keras.layers.Dense(60, input_dim = 60, activation = "relu"),
#     keras.layers.Dense(30, activation = "relu"),
#     keras.layers.Dense(15, activation = "relu"),
#     keras.layers.Dense(15, activation = "sigmoid"),
# ])
# model.compile(loss = "binary_crossentropy", optimizer = "adam", metrics= ["accuracy"])
# model.fit(X_train, y_train, epochs = 100, batch_size = 8)

model = keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 6s 4ms/step - loss: 0.6871 - accuracy: 0.5192
Epoch 2/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6625 - accuracy: 0.6474
Epoch 3/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6425 - accuracy: 0.5897
Epoch 4/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6133 - accuracy: 0.7436
Epoch 5/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5763 - accuracy: 0.7179
Epoch 6/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5606 - accuracy: 0.7564
Epoch 7/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5162 - accuracy: 0.7949
Epoch 8/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4792 - accuracy: 0.8333
Epoch 9/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4762 - accuracy: 0.7821
Epoch 10/100
20/20 [==============================] - 0s 7ms/step - loss: 0.4299 - accuracy: 0.8333
Epoch 11/

In [30]:
model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 8ms/step - loss: 1.3126 - accuracy: 0.7500


[1.3125567436218262, 0.75]

In [33]:
y_pred  = model.predict(X_test).reshape(-1)
print(y_pred[:10])

2/2 [==============================] - 0s 5ms/step
[8.5840376e-11 9.9758339e-01 9.9870908e-01 1.8255985e-05 9.9999642e-01
 9.9846041e-01 2.3879292e-03 9.9999619e-01 2.2261358e-07 9.9999917e-01]


In [34]:

y_pred = np.round(y_pred)
print(y_pred[:10])

[0. 1. 1. 0. 1. 1. 0. 1. 0. 1.]


In [37]:
y_test[:10]

R
186  0
155  0
165  0
200  0
58   1
34   1
151  0
18   1
202  0
62   1

In [39]:
from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.72      0.85      0.78        27
           1       0.80      0.64      0.71        25

    accuracy                           0.75        52
   macro avg       0.76      0.75      0.75        52
weighted avg       0.76      0.75      0.75        52



In [45]:
# Model with dropout Layers
from tensorflow import keras

modeld =keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation = "relu"),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(30, activation = "relu"),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(15, activation = "relu"),
    keras.layers.Dropout (0.5),
    keras.layers.Dense(1, activation = "sigmoid")
])
modeld.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
modeld.fit(X_train, y_train, epochs = 100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 3s 4ms/step - loss: 0.7404 - accuracy: 0.4872
Epoch 2/100
20/20 [==============================] - 0s 4ms/step - loss: 0.7277 - accuracy: 0.4808
Epoch 3/100
20/20 [==============================] - 0s 4ms/step - loss: 0.7272 - accuracy: 0.4551
Epoch 4/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6858 - accuracy: 0.5833
Epoch 5/100
20/20 [==============================] - 0s 4ms/step - loss: 0.7156 - accuracy: 0.4615
Epoch 6/100
20/20 [==============================] - 0s 4ms/step - loss: 0.7021 - accuracy: 0.5321
Epoch 7/100
20/20 [==============================] - 0s 4ms/step - loss: 0.7001 - accuracy: 0.4744
Epoch 8/100
20/20 [==============================] - 0s 4ms/step - loss: 0.7045 - accuracy: 0.4808
Epoch 9/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6939 - accuracy: 0.5064
Epoch 10/100
20/20 [==============================] - 0s 4ms/step - loss: 0.7016 - accuracy: 0.5128
Epoch 11/

In [46]:
modeld.evaluate(X_test, y_test)

2/2 [==============================] - 0s 12ms/step - loss: 0.4587 - accuracy: 0.7692


[0.4587068259716034, 0.7692307829856873]

In [47]:
y_pred - modeld.predict(X_test).reshape(-1)
print(y_pred[:10])

y_pred = np.round(y_pred)
print(y_pred[:10])

2/2 [==============================] - 0s 5ms/step
[0. 1. 1. 0. 1. 1. 0. 1. 0. 1.]
[0. 1. 1. 0. 1. 1. 0. 1. 0. 1.]


In [51]:
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.72      0.85      0.78        27
           1       0.80      0.64      0.71        25

    accuracy                           0.75        52
   macro avg       0.76      0.75      0.75        52
weighted avg       0.76      0.75      0.75        52



In [52]:
# Hence the performance has imporoved as we can see while using the dropotut layer technique